plugins:
  - flowtype
extends:
  - "@enkidevs/eslint-config-backend"
  - plugin:flowtype/recommended
parser: babel-eslint
rules:
  node/no-unsupported-features/es-syntax: 0
  no-unused-vars: 1
  no-new: 0
globals:
  localStorage: true
