extends:
  - '@enkidevs/eslint-config-backend'
  - plugin:flowtype/recommended
parser: babel-eslint
plugins:
  - flowtype
rules:
  node/no-unsupported-features/es-syntax: off
  no-unused-vars: warn
  no-new: off
globals:
  localStorage: true
