export const ADD_POST = 'posts.ADD_POST'
export const FETCH_POSTS = 'posts.FETCH_POSTS'
export const ADD_COMMENT = 'comments.ADD_COMMENT'
export const FETCH_COMMENTS = 'comments.FETCH_COMMENTS'
export const UPDATE_COMMENT = 'comments.UPDATE_COMMENT'
